[package]
name = "lsmdb-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.138"
crossbeam-epoch = "0.9"
crossbeam-skiplist = "0.1"

lsmdb-storage = { version = "0.1.0", path = "../storage" }
